In [2]:
#Question1:


import numpy as np
x=np.array([1,2,3,4])
y=np.array([5.5,6.5,7.5,8.5])
print(np.add(x,y))
print(np.subtract(x,y))

print(np.multiply(x,y))

print(np.divide(x,y))

[ 6.5  8.5 10.5 12.5]
[-4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34. ]
[0.18181818 0.30769231 0.4        0.47058824]


In [4]:
#Question2:

X = np.array([[1,2],[3,4]])
print(np.sqrt(X))

print(np.min(X,axis=1))

print(np.max(X,axis=1))

print(np.min(X,axis=0))

print(np.max(X,axis=0))

print(X.std())

print(np.exp(X))

print(X.mean())

print(np.median(X))


[[1.         1.41421356]
 [1.73205081 2.        ]]
[1 3]
[2 4]
[1 2]
[3 4]
1.118033988749895
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
2.5
2.5
